plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace 'com.example.wgpllocation'
    compileSdk 36

    defaultConfig {
        applicationId "com.example.wgpllocation"
        minSdk 24
        targetSdk 36
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}

dependencies {
    implementation libs.appcompat
    implementation libs.material
    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core
    implementation files('libs/jtds-1.2.5.jar')
    compileOnly fileTree(include: ['com.symbol.emdk.jar'], dir: 'C:\\Users\\victor.avalos\\AppData\\Local\\Android\\Sdk\\add-ons\\addon-symbol_emdk-symbol-26\\libs')
    implementation fileTree(exclude: ['com.symbol.emdk.jar'], dir: 'libs')
}